AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon S3 trigger that uses OpenCV to stabilize videos.
Parameters:
  InBucketName:
    Type: String
    Description: Name of the bucket that should be watched for events.
  OutBucketName:
    Type: String
    Description: Name of the bucket that should be used as the output.
  BorderType:
    Type: String
    Default: black
    AllowedValues:
      - black
      - reflect
      - replicate
    Description: The border that should be used when stabilizing the videos.
  BorderSize:
    Type: Number
    Default: 0
    Description: The size of the border surounding the black border. Not needed for reflect and replicate.
  KeypointDetectorMethod:
    Type: String
    Default: GFTT
    AllowedValues:
      - GFTT
      - BRISK
      - DENSE
      - FAST
      - HARRIS
      - MSER
      - ORB
      - STAR
    Description: Which method
Resources:
  vidstabpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://robrose-serverless-repo/dist/stabVideo.zip
      Description: An Amazon S3 trigger that uses OpenCV to stabilize videos.
      MemorySize: 512
      Timeout: 60
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref InBucketName
        - S3CrudPolicy:
            BucketName: !Ref OutBucketName
      Events:
        ObjectCreatedBucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref WatchBucket
            Events:
              - 's3:ObjectCreated:*'

      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutBucketName
          KP_METHOD: !Ref KeypointDetectorMethod
          BORDER_TYPE: !Ref BorderType
          BORDER_SIZE: !Ref BorderSize

  WatchBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref InBucketName

  OutputBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref OutBucketName
