AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon S3 trigger that uses rekognition APIs to detect faces and then blurs them.
Parameters:
  BorderType:
    Type: String
    Default: black
    AllowedValues:
      - black
      - reflect
      - replicate
    Description: The border that should be used when stabilizing the videos.
  BorderSize:
    Type: Number
    Default: 0
    Description: The size of the border surounding the black border. Not needed for reflect and replicate.
  KeypointDetectorMethod:
    Type: String
    Default: GFTT
    AllowedValues:
      - GFTT
      - BRISK
      - DENSE
      - FAST
      - HARRIS
      - MSER
      - ORB
      - SIFT
      - SURF
      - STAR
    Description: Which method
Resources:
  WatchBucket:
    Type: 'AWS::S3::Bucket'

  OutputBucket:
    Type: 'AWS::S3::Bucket'

  vidstabpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri:
        Bucket: robrose-code-packages/
        Key: serverlesshack/stabVideo.zip
      Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
      MemorySize: 1280
      Timeout: 60
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref WatchBucket
        - S3CrudPolicy:
            BucketName: !Ref OutputBucket
      Events:
        ObjectCreatedBucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: WatchBucket
            Events:
              - 's3:ObjectCreated:*'

      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucket
          KP_METHOD: !Ref KeypointDetectorMethod
          BORDER_TYPE: !Ref BorderType
          BORDER_SIZE: !Ref BorderSize
