AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon S3 trigger that uses rekognition APIs to detect faces and then blurs them.

Resources:
  WatchBucket:
    Type: 'AWS::S3::Bucket'

  OutputBucket:
    Type: 'AWS::S3::Bucket'

  rekognitionpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri:
        Bucket: robrose-serverless-repo/
        Key: dist/blurFaces.zip
      Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
      MemorySize: 1280
      Timeout: 60
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref WatchBucket
        - S3CrudPolicy:
            BucketName: !Ref OutputBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'rekognition:DetectFaces'
              Resource: '*'
      Events:
        ObjectCreatedBucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: WatchBucket
            Events:
              - 's3:ObjectCreated:*'

      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucket

