AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon S3 trigger that uses rekognition APIs to detect faces and then blurs them.

Parameters:

  ConfThreshold:
    Description: The minimum confidence Rekognition should have for a given face. Float between 0 and 1.
    MinValue: 0.0
    MaxValue: 1.0
    Type: Number
    Default: 0.90

  FillColor:
    Description: The color we should fill the faces with.
    AllowedPattern: '^#?(?:[0-9a-fA-F]{3}){1,2}$'
    Default: '#FFF'

Resources:
  rekognitionpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
            - Effect: Allow
              Action:
                - 'rekognition:DetectFaces'
              Resource: '*'
      Events:
        ObjectCreatedBucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
  WatchBucket:
    Type: 'AWS::S3::Bucket'

  OutputBucket:
    Type: 'AWS::S3::Bucket'
